version: '3.8'

services:
  # Include services from backend/docker-compose.yml
  backend:
    extends:
      file: backend/docker-compose.yml
      service: backend

  # Include services from frontend/docker-compose.yml
  frontend:
    extends:
      file: frontend/docker-compose.yml
      service: frontend

networks:
  default:
    name: apps-network
    driver: bridge
